//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BonCake.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BonCakeEntities1 : DbContext
    {
        public BonCakeEntities1()
            : base("name=BonCakeEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BannerIndex> BannerIndex { get; set; }
        public virtual DbSet<CakeImages> CakeImages { get; set; }
        public virtual DbSet<CakeParts> CakeParts { get; set; }
        public virtual DbSet<CakeShopCar> CakeShopCar { get; set; }
        public virtual DbSet<CakeShops> CakeShops { get; set; }
        public virtual DbSet<CakeTypes> CakeTypes { get; set; }
        public virtual DbSet<LoginUsers> LoginUsers { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<Verification> Verification { get; set; }
    }
}
