//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BonCake.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CakeShops
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CakeShops()
        {
            this.CakeShopCar = new HashSet<CakeShopCar>();
        }
    
        public int cakeId { get; set; }
        public string cakeSize { get; set; }
        public string cakeEnName { get; set; }
        public string cakeChName { get; set; }
        public int cakePrice { get; set; }
        public string cakeType { get; set; }
        public string cakeTest { get; set; }
        public string cakeImg { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CakeShopCar> CakeShopCar { get; set; }
    }
}
