//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BonCake.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CakeParts
    {
        public int partsId { get; set; }
        public string partsEnName { get; set; }
        public string partsChName { get; set; }
        public int partsPrice { get; set; }
        public string partsImg { get; set; }
    }
}
